{% set name = "auth0-python" %}
{% set version = "3.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auth0-python-{{ version }}.tar.gz
  sha256: 2ad17af5f0099f687cc6707ef2049364b5058c18db14e2a0a85a0eedf83ea627

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.2
    - pip
  run:
    - python >=3.2
    - requests

test:
  imports:
    - auth0
    - auth0.v3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/auth0/auth0-python
  summary: Auth0 Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
